#!/bin/bash
# Builds the semantic-map probe from the live app sources.
#
# Same source slicing as Tools/InterpretationProbe/build.sh, plus two files cut
# out of the live ThoughtExtractor.swift at every build so the Phase 1 trace
# runs production's own model route rather than a hand copy of it:
#
#   ProductionRefinementMirror.swift  `IntelligentThoughtExtractor`, renamed,
#                                     with `private` removed so validation and
#                                     grounding can be called one at a time
#   ProductionRefinementPrompt.swift  the instructions literal from its `extract`
#
# and it refuses to build when either of the two literals the trace has to
# restate (the two-second budget, the prompt prefix) no longer reads the way
# ProductionRoute.swift assumes. A mirror that silently stopped mirroring is
# the failure this build exists to prevent.
#
# It links FoundationModels when the toolchain has it; the binary runs either
# way. `--census`, `--selfcheck` and `--replay` need no model.
set -euo pipefail
SP="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SP/../.." && pwd)"
OUT="${PROBE_OUT:-$SP/build}"
GEN="$OUT/generated"
mkdir -p "$GEN"
cd "$ROOT"

EXTRACTOR=SpeakIt/Repositories/ThoughtExtractor.swift

refuse() { echo "semantic-map build: $*" >&2; exit 1; }

grep -q 'try? await Task.sleep(for: .seconds(2))' "$EXTRACTOR" \
  || refuse "the refinement budget in $EXTRACTOR is no longer .seconds(2); update productionBudgetMilliseconds in Sources/ProductionRoute.swift"
grep -qF 'to: "Organize this transcript:\n\(transcript)",' "$EXTRACTOR" \
  || refuse "the refinement prompt prefix in $EXTRACTOR changed; update productionPromptPrefix in Sources/ProductionRoute.swift"
grep -q 'guard !transcript.isEmpty, transcript.count <= 1_500 else { return false }' "$EXTRACTOR" \
  || refuse "RefinementPolicy's length gate changed; update RoutePolicyReason decomposition in Sources/ProductionRoute.swift"

# The mirror: from `enum IntelligentThoughtExtractor {` to its closing brace at
# column zero, inside the same availability and import guards production uses.
START=$(grep -n '^enum IntelligentThoughtExtractor {' "$EXTRACTOR" | cut -d: -f1)
[ -n "$START" ] || refuse "IntelligentThoughtExtractor not found in $EXTRACTOR"
END=$(awk -v s="$START" 'NR>s && /^}/ {print NR; exit}' "$EXTRACTOR")
AVAIL=$(sed -n "$((START - 1))p" "$EXTRACTOR")
case "$AVAIL" in
  "@available("*) ;;
  *) refuse "the line above IntelligentThoughtExtractor is no longer its @available attribute" ;;
esac
{
  echo "// GENERATED by Tools/SemanticMap/build.sh from $EXTRACTOR:$START-$END. Do not edit."
  echo "import Foundation"
  echo "#if canImport(FoundationModels)"
  echo "import FoundationModels"
  echo "$AVAIL"
  sed -n "${START},${END}p" "$EXTRACTOR" \
    | sed -e 's/^enum IntelligentThoughtExtractor {/enum ProductionRefinementMirror {/' \
          -e 's/private static func/static func/'
  echo "#endif"
} > "$GEN/ProductionRefinementMirror.swift"
grep -q 'static func validate(' "$GEN/ProductionRefinementMirror.swift" || refuse "validate(...) not found in the mirror"
grep -q 'static func isGrounded(' "$GEN/ProductionRefinementMirror.swift" || refuse "isGrounded(...) not found in the mirror"
grep -q 'static func normalizedForGrounding(' "$GEN/ProductionRefinementMirror.swift" || refuse "normalizedForGrounding(...) not found in the mirror"
grep -Eq '^[[:space:]]*(file)?private[[:space:]]' "$GEN/ProductionRefinementMirror.swift" && refuse "the mirror still has a private member the trace cannot reach"

# The instructions literal: the lines strictly between `let instructions = """`
# and the next line that is only `"""`, inside the mirrored range.
ISTART=$(awk -v s="$START" -v e="$END" 'NR>s && NR<e && /let instructions = """$/ {print NR; exit}' "$EXTRACTOR")
[ -n "$ISTART" ] || refuse "the instructions literal in IntelligentThoughtExtractor.extract moved"
IEND=$(awk -v s="$ISTART" 'NR>s && /^[[:space:]]*"""[[:space:]]*$/ {print NR; exit}' "$EXTRACTOR")
{
  echo "// GENERATED by Tools/SemanticMap/build.sh from $EXTRACTOR:$ISTART-$IEND. Do not edit."
  echo "enum ProductionRefinementPrompt {"
  echo "    static let instructions = \"\"\""
  sed -n "$((ISTART + 1)),$((IEND - 1))p" "$EXTRACTOR"
  # The closing delimiter keeps production's indentation, which is what Swift
  # strips from every line: a different indent would change the text.
  sed -n "${IEND}p" "$EXTRACTOR"
  echo "}"
} > "$GEN/ProductionRefinementPrompt.swift"

# Which commit produced a run, carried in every record it writes.
COMMIT=$(git rev-parse --short=12 HEAD 2>/dev/null || echo unknown)
DIRTY=false
if [ -n "$(git status --porcelain -- SpeakIt Tools/SemanticMap Tools/PipelineProbe 2>/dev/null)" ]; then DIRTY=true; fi
{
  echo "// GENERATED by Tools/SemanticMap/build.sh. Do not edit."
  echo "let buildCommit = \"$COMMIT\""
  echo "let buildTreeDirty = $DIRTY"
} > "$GEN/BuildInfo.swift"

START=$(grep -n '^enum ReminderCopy {' SpeakIt/Repositories/ReminderScheduler.swift | cut -d: -f1)
END=$(awk -v s="$START" 'NR>s && /^}/ {print NR; exit}' SpeakIt/Repositories/ReminderScheduler.swift)
{ echo "import Foundation"; sed -n "${START},${END}p" SpeakIt/Repositories/ReminderScheduler.swift; } > "$GEN/ReminderCopySlice.swift"

CUT=$(grep -n "^// MARK: - Memory.s reading of the same question" SpeakIt/Repositories/PersonMention.swift | cut -d: -f1)
sed -n "1,$((CUT - 1))p" SpeakIt/Repositories/PersonMention.swift > "$GEN/PersonMentionSlice.swift"

LCUT=$(grep -n "^/// Turns a location intent into something monitorable" SpeakIt/Models/LocationIntent.swift | cut -d: -f1)
sed -n "1,$((LCUT - 1))p" SpeakIt/Models/LocationIntent.swift > "$GEN/LocationIntentSlice.swift"

DEVELOPER_DIR="${DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}" xcrun swiftc -O -o "$OUT/semantic-map" \
  SpeakIt/Repositories/ClauseStructure.swift \
  SpeakIt/Repositories/TranscriptProvenance.swift \
  SpeakIt/Repositories/ThoughtExtractor.swift \
  SpeakIt/Repositories/ThoughtOrganizer.swift \
  SpeakIt/Repositories/SpeechRepair.swift \
  SpeakIt/Repositories/IntentConsolidation.swift \
  SpeakIt/Repositories/Actionability.swift \
  "$GEN/PersonMentionSlice.swift" \
  SpeakIt/Repositories/LocationIntentParser.swift \
  SpeakIt/Repositories/CaptureOperationCopy.swift \
  SpeakIt/Features/Shopping/ShoppingGroups.swift \
  SpeakIt/Models/DomainEnums.swift \
  SpeakIt/Models/CaptureOperation.swift \
  "$GEN/LocationIntentSlice.swift" \
  SpeakIt/Models/TemporalIntent.swift \
  SpeakIt/Models/ReminderTrigger.swift \
  "$GEN/ReminderCopySlice.swift" \
  "$GEN/ProductionRefinementMirror.swift" \
  "$GEN/ProductionRefinementPrompt.swift" \
  "$GEN/BuildInfo.swift" \
  Tools/PipelineProbe/shims.swift \
  Tools/PipelineProbe/rowreport.swift \
  "$SP/Sources/Atoms.swift" \
  "$SP/Sources/SemanticMap.swift" \
  "$SP/Sources/SemanticJobs.swift" \
  "$SP/Sources/ComplexityFeatures.swift" \
  "$SP/Sources/Arbiter.swift" \
  "$SP/Sources/ProductionRoute.swift" \
  "$SP/Sources/Records.swift" \
  "$SP/Sources/SelfCheck.swift" \
  "$SP/Sources/main.swift" 2> "$OUT/build-errors.log" || { cat "$OUT/build-errors.log" >&2; exit 1; }
test -x "$OUT/semantic-map" && echo "semantic-map probe built: $OUT/semantic-map ($COMMIT$([ "$DIRTY" = true ] && echo ', dirty tree'))"
