import Foundation
@testable import SpeakIt

/// Corpus families 17-21, ending with the compositions.
///
/// The first four families here finish the per-feature coverage: deadlines
/// against reminders, alarms against notifications, events, and the pronouns
/// and possessives that decide who a capture is about.
///
/// `compositions` is the reason this file exists. Every earlier family varies
/// one thing at a time, which is how a parser is *built*; it is not how a
/// parser is used. Real dictation stacks a correction on top of a recurrence
/// inside a sentence that also cancels something else, and features that each
/// pass alone can still combine into the wrong item. Those interactions are
/// what is left to find.
///
/// Reference instant unchanged: Monday 2026-08-03 10:00 America/Toronto.
enum SemanticCorpusD {

    // MARK: - Deadlines, and reminders that are not deadlines
    //
    // `dueDate` is when the thing is owed. `reminderDate` is when to speak up.
    // They are different fields, they are frequently both present in one
    // sentence, and collapsing them either nags on the wrong day or says
    // nothing until the work is already late.
    static let deadlines: [CorpusCase] = [
        corpusCase(.deadlines, "The report is due Friday, remind me Thursday morning", count: 1,
                   due: [CorpusDate(month: 8, day: 7, hour: nil)],
                   remind: [CorpusDate(month: 8, day: 6, hour: 9)]),
        corpusCase(.deadlines, "Due the 15th, remind me the 14th", count: 1,
                   due: [CorpusDate(month: 8, day: 15, hour: nil)],
                   remind: [CorpusDate(month: 8, day: 14, hour: 9)]),
        corpusCase(.deadlines, "Remind me Thursday about the Friday deadline", count: 1,
                   due: [CorpusDate(month: 8, day: 7, hour: nil)],
                   remind: [CorpusDate(month: 8, day: 6, hour: 9)],
                   note: "The same two dates as the case above, stated in the opposite order. Position must not decide which field a date lands in."),
        corpusCase(.deadlines, "Finish the deck by Thursday", count: 1, delivery: [.none],
                   due: [CorpusDate(month: 8, day: 6, hour: nil)], remind: [nil]),
        corpusCase(.deadlines, "Turn in the form before Wednesday", count: 1,
                   due: [CorpusDate(month: 8, day: 5, hour: nil)], remind: [nil]),
        corpusCase(.deadlines, "Application closes Friday", count: 1,
                   due: [CorpusDate(month: 8, day: 7, hour: nil)], remind: [nil]),
        corpusCase(.deadlines, "Submit by 5 PM Friday", count: 1, kind: [.exactDateTime],
                   due: [CorpusDate(month: 8, day: 7, hour: 17)]),
        corpusCase(.deadlines, "I need the visa application in by the 25th", count: 1,
                   due: [CorpusDate(month: 8, day: 25, hour: nil)]),
        corpusCase(.deadlines, "Rent is due on the first", count: 1,
                   due: [CorpusDate(month: 9, day: 1, hour: nil)],
                   note: "The next first, which is next month. A day number already past this month does not mean a date in the past."),
        corpusCase(.deadlines, "The deadline moved from Friday to Monday", count: 1,
                   due: [CorpusDate(month: 8, day: 10, hour: nil)],
                   note: "Monday is the result, Friday is the origin. Same shape as \"the meeting moved from Tuesday to Thursday\"."),
        corpusCase(.deadlines, "The assignment is due at midnight Friday", count: 1,
                   due: [CorpusDate(month: 8, day: 7, hour: 0)], severityCeiling: .metadata,
                   note: "Arguable: \"midnight Friday\" is the start of Friday by the clock and the end of it in ordinary speech. Recorded, not gated."),
        corpusCase(.deadlines, "Finish the deck by end of day", count: 1,
                   due: [CorpusDate(month: 8, day: 3, hour: nil)], severityCeiling: .metadata,
                   note: "Arguable: today, but whether that carries a closing hour is undecided. Recorded, not gated."),
        corpusCase(.deadlines, "Pay the invoice within 30 days", count: 1,
                   due: [CorpusDate(month: 9, day: 2, hour: nil)], remind: [nil],
                   note: "Decided 2026-09-08: a closed window is a deadline, and its last day is when the thing is due — date-only, like \"by Friday\". \"In 30 days\" is a point and keeps its clock."),
        corpusCase(.deadlines, "Renew the permit within two weeks", count: 1,
                   due: [CorpusDate(month: 8, day: 17, hour: nil)], remind: [nil]),
        corpusCase(.deadlines, "Finish the report in the next 3 days", count: 1,
                   due: [CorpusDate(month: 8, day: 6, hour: nil)], remind: [nil]),
        corpusCase(.deadlines, "Remind me the day before the report is due", count: 1, review: [true],
                   note: "Relative to a date the app was never told. Ask; do not invent an anchor."),
        corpusCase(.deadlines, "Remind me two days before the exam", count: 1, review: [true]),
        corpusCase(.deadlines, "Remind me an hour before the meeting", count: 1, review: [true],
                   note: "The neighbour of \"remind me in an hour\", which resolves. \"Before the meeting\" has no anchor."),
        corpusCase(.deadlines, "Remind me a week before my passport expires", count: 1, review: [true]),
        corpusCase(.deadlines, "Renew the insurance sometime before September", count: 1,
                   severityCeiling: .metadata,
                   note: "Arguable: a month boundary is a deadline of sorts. Recorded, not gated."),
    ]

    // MARK: - Alarms
    //
    // Delivery is inferred from the words and never persisted, so it has to be
    // re-derived correctly every time. An alarm that arrives as a notification
    // is silent when the person needed to be woken.
    static let alarms: [CorpusCase] = [
        corpusCase(.alarms, "Wake me up at 6:30", count: 1, delivery: [.alarm],
                   remind: [CorpusDate(month: 8, day: 4, hour: 6, minute: 30)],
                   note: "\"Wake me\" is an alarm and it is unambiguously morning."),
        corpusCase(.alarms, "Wake me at 5 tomorrow morning", count: 1, delivery: [.alarm],
                   remind: [CorpusDate(month: 8, day: 4, hour: 5)]),
        corpusCase(.alarms, "Set an alarm for 5:45 tomorrow", count: 1, delivery: [.alarm],
                   remind: [CorpusDate(month: 8, day: 4, hour: 5, minute: 45)]),
        corpusCase(.alarms, "Set an alarm for noon", count: 1, delivery: [.alarm],
                   remind: [CorpusDate(month: 8, day: 3, hour: 12)]),
        corpusCase(.alarms, "Set an alarm for the meeting at 3", count: 1, delivery: [.alarm],
                   remind: [CorpusDate(month: 8, day: 3, hour: 15)]),
        corpusCase(.alarms, "Alarm for 45 minutes from now", count: 1, delivery: [.alarm],
                   kind: [.relativeDuration], remind: [CorpusDate(month: 8, day: 3, hour: 10, minute: 45)]),
        corpusCase(.alarms, "Alarm at 7 every weekday", count: 1, delivery: [.alarm],
                   recurs: [CorpusRecurrence(frequency: .weekly, interval: 1, weekdays: [2, 3, 4, 5, 6])]),
        corpusCase(.alarms, "Set an alarm every morning at 6", count: 1, delivery: [.alarm],
                   remind: [CorpusDate(month: 8, day: 4, hour: 6)],
                   recurs: [CorpusRecurrence(frequency: .daily, interval: 1)]),
        corpusCase(.alarms, "Set two alarms, 6:30 and 6:45", count: 2, delivery: [.alarm, .alarm]),
        corpusCase(.alarms, "Cancel my 7 AM alarm", count: 0, operation: [.cancel]),
        corpusCase(.alarms, "Set an alarm for 6", count: 1, delivery: [.alarm],
                   note: "Split during review. Which 6 is genuinely arguable; that this is an alarm at all is not, and a ceiling on the whole case was shielding the unarguable half."),
        corpusCase(.alarms, "Set an alarm for 6", count: 1,
                   remind: [CorpusDate(month: 8, day: 4, hour: 6)],
                   note: "Decided during this pass. The general bare-hour rule picks the next occurrence, which would be 6 PM tonight; an alarm is the one context where that rule is reliably wrong, because alarms are set for the morning. So an alarm hour between 4 and 11 is committed to AM and rolls to tomorrow."),

        // Counterexamples. Delivery is a three-way choice and the other two
        // legs have to survive the alarm rule.
        corpusCase(.alarms, "Remind me at 7 AM", count: 1, delivery: [.notification],
                   remind: [CorpusDate(month: 8, day: 4, hour: 7)],
                   note: "Identical instant to an alarm, different delivery. \"Remind me\" is never an alarm."),
        corpusCase(.alarms, "Buy an alarm clock", count: 1, type: [.shopping], route: [.today],
                   delivery: [.none], remind: [nil],
                   note: "The word \"alarm\" as a noun in a shopping item. Nothing is scheduled."),
        corpusCase(.alarms, "The fire alarm test is Thursday", count: 1, delivery: [.none],
                   due: [CorpusDate(month: 8, day: 6, hour: nil)], remind: [nil]),
    ]

    // MARK: - Events
    //
    // A commitment on the calendar. Nothing has to be performed, so an event
    // must not acquire a notification it was never asked for, and it must not
    // lose the clock it was given.
    static let events: [CorpusCase] = [
        corpusCase(.events, "Grab lunch with Sam at noon", count: 1, type: [.event], route: [.today],
                   person: ["Sam"], delivery: [.none],
                   due: [CorpusDate(month: 8, day: 3, hour: 12)]),
        corpusCase(.events, "Get dinner with Maya tomorrow", count: 1, type: [.event], route: [.today],
                   person: ["Maya"], delivery: [.none],
                   due: [CorpusDate(month: 8, day: 4, hour: nil)]),
        corpusCase(.events, "Dentist appointment Thursday at 10", count: 1, type: [.event], route: [.today],
                   delivery: [.none], due: [CorpusDate(month: 8, day: 6, hour: 10)]),
        corpusCase(.events, "Team standup tomorrow at 9:30", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 4, hour: 9, minute: 30)]),
        corpusCase(.events, "Interview at 2 on Tuesday", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 4, hour: 14)],
                   note: "Time before day. Order must not change the instant."),
        corpusCase(.events, "Lunch with Alex Friday at 12:30", count: 1, route: [.today], person: ["Alex"],
                   due: [CorpusDate(month: 8, day: 7, hour: 12, minute: 30)]),
        corpusCase(.events, "Coffee with Priya tomorrow", count: 1, route: [.today], person: ["Priya"],
                   due: [CorpusDate(month: 8, day: 4, hour: nil)]),
        corpusCase(.events, "The game starts at 7:30 tonight", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 3, hour: 19, minute: 30)]),
        corpusCase(.events, "Concert Saturday night", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 8, hour: 20)]),
        corpusCase(.events, "I have a meeting Friday morning", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 7, hour: 9)]),
        corpusCase(.events, "Dinner reservation at 8 on the 14th", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 14, hour: 20)]),
        corpusCase(.events, "Flight to Vancouver on the 12th", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 12, hour: nil)], remind: [nil]),
        corpusCase(.events, "Parent teacher conference next Thursday at 6", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 13, hour: 18)],
                   note: "\"Next Thursday\" is the following calendar week, same contract as \"next Friday\"."),
        corpusCase(.events, "Doctor's appointment moved to Wednesday", count: 1,
                   due: [CorpusDate(month: 8, day: 5, hour: nil)]),
        corpusCase(.events, "Catherine's wedding is in September", count: 1, route: [.memory],
                   person: ["Catherine"], remind: [nil],
                   note: "A month with no day is knowledge, not a commitment. Same shape as \"Catherine's birthday is in March\"."),
        corpusCase(.events, "Book club every second Tuesday", count: 1,
                   recurs: [CorpusRecurrence(frequency: .weekly, interval: 2, weekdays: [3])],
                   note: "Decided 2026-09-08: \"every second Tuesday\" is \"every other Tuesday\" in the English spoken here. The monthly reading needs \"of the month\", which the ordinal rule already claims."),
        corpusCase(.events, "Book club every second week", count: 1,
                   recurs: [CorpusRecurrence(frequency: .weekly, interval: 2)]),
        corpusCase(.events, "The conference is the 10th through the 12th", count: 1,
                   due: [CorpusDate(month: 8, day: 10, hour: nil)], severityCeiling: .metadata,
                   note: "Arguable: date ranges are unmodelled, so the start date is the best available answer. Recorded, not gated."),
        corpusCase(.events, "Standup moved from 9 to 9:30", count: 1, type: [.event], person: [nil],
                   due: [CorpusDate(month: 8, day: 4, hour: 9, minute: 30)],
                   note: "Decided 2026-09-08: the new time is the one behind \"to\", and \"9 to 9:30\" is not nine minutes to nine. 9:30 today is already past at the 10 AM reference, so the next one is tomorrow. The standup is a thing whose time changed, not somebody who relocated."),
        corpusCase(.events, "Meeting moved from 2 to 3", count: 1, type: [.event], person: [nil],
                   due: [CorpusDate(month: 8, day: 3, hour: 15, minute: 0)]),
        corpusCase(.events, "Dinner moved to 7", count: 1, type: [.event], route: [.today],
                   due: [CorpusDate(month: 8, day: 3, hour: 19, minute: 0)],
                   note: "Was a Memory note: \"moved\" read as a life event with nothing scheduled in it."),
        corpusCase(.events, "Meeting from 2 to 3", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 3, hour: 14, minute: 0)],
                   note: "A span starts when it starts. \"2 to 3\" used to read as two minutes to three, and \"from 9 to 9:30\" as 8:51 PM."),
        corpusCase(.events, "Alex moved to 5 Main Street", count: 1, route: [.memory], person: ["Alex"],
                   due: [nil], note: "An address is not a clock: a person who moved is a fact about them."),
        // Appointments keep business hours. A bare hour otherwise means its
        // next occurrence, which is right for "call Sam at 9" (pinned at 21:00
        // in the temporal family) and wrong for anything a clinic schedules.
        corpusCase(.events, "Dentist at 8", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 4, hour: 8, minute: 0)],
                   note: "Was 8 PM tonight."),
        corpusCase(.events, "Meeting at 9", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 4, hour: 9, minute: 0)],
                   note: "Was 9 PM tonight, the next occurrence of a bare 9 said at ten."),
        corpusCase(.events, "The first appointment is at 9", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 4, hour: 9, minute: 0)],
                   note: "Domains C4 d, closed: a passed appointment hour is tomorrow morning's, not tonight's."),
        corpusCase(.events, "Interview at 10", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 4, hour: 10, minute: 0)]),
        corpusCase(.events, "Meeting at 7", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 3, hour: 19, minute: 0)],
                   note: "7 keeps the general rule: a 7 PM meeting is ordinary and a 7 AM one is not."),
        corpusCase(.events, "Dinner meeting at 8", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 3, hour: 20, minute: 0)],
                   note: "The evening noun is read first, so the meeting keeps its dinner."),
        // A clock carrying its meridiem is a time whatever stands in front of
        // it; these were Memory notes for want of an "at".
        corpusCase(.events, "Standup 9am", count: 1, type: [.event], route: [.today],
                   due: [CorpusDate(month: 8, day: 4, hour: 9, minute: 0)]),
        corpusCase(.events, "Dentist 2pm", count: 1, type: [.event], route: [.today],
                   due: [CorpusDate(month: 8, day: 3, hour: 14, minute: 0)]),
        // Two dated noun phrases are two events, and a day at the end scopes
        // over both clocks. "At 2 and at 4" has one object and stays one.
        corpusCase(.events, "Gym at 6 and dinner at 8", count: 2, route: [.today, .today],
                   due: [CorpusDate(month: 8, day: 3, hour: 18, minute: 0), CorpusDate(month: 8, day: 3, hour: 20, minute: 0)],
                   note: "Was one event at 6 with the dinner inside its title."),
        corpusCase(.events, "Lunch at 12 and dinner at 8 tomorrow", count: 2,
                   due: [CorpusDate(month: 8, day: 4, hour: 12, minute: 0), CorpusDate(month: 8, day: 4, hour: 20, minute: 0)]),
        corpusCase(.events, "Meeting at 2 and at 4", count: 1,
                   due: [CorpusDate(month: 8, day: 3, hour: 14, minute: 0)]),
        // A thing that has turned up is history however plainly the day is
        // stated; a thing still coming is not.
        corpusCase(.events, "The parcel arrived Friday", count: 1, route: [.memory], due: [nil],
                   note: "Was an event dated next Friday."),
        corpusCase(.events, "The guests arrive Friday", count: 1, type: [.event], route: [.today],
                   due: [CorpusDate(month: 8, day: 7, hour: nil)]),
        // Authored 2026-09-09 from a batch of everyday captures.
        corpusCase(.events, "Book a table for four at 7 on Friday", count: 1,
                   due: [CorpusDate(month: 8, day: 7, hour: 19, minute: 0)],
                   note: "Was 4 PM: the party size behind \"for\" won over the clock behind \"at\"."),
        corpusCase(.events, "Physio Wednesday 10:15", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 5, hour: 10, minute: 15)],
                   note: "A colon makes a clock of a number with no preposition; this was day-only."),
        corpusCase(.events, "The score was 3:1", count: 1, route: [.memory], due: [nil]),
        corpusCase(.events, "Movie night Friday", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 7, hour: nil)],
                   note: "\"Night\" in a compound names the kind of evening, not a clock; this invented 8 PM."),
        corpusCase(.events, "Friday night dinner with Sam", count: 1, type: [.event],
                   due: [CorpusDate(month: 8, day: 7, hour: 20, minute: 0)]),
        corpusCase(.events, "The parking pass expires Friday", count: 1, type: [.event], route: [.today],
                   due: [CorpusDate(month: 8, day: 7, hour: nil)],
                   note: "An expiry on a named day is the last moment to act, as \"the offer ends Friday\" already was."),
        corpusCase(.events, "My passport expires in March", count: 1, route: [.memory], due: [nil],
                   note: "A month is knowledge, the birthday rule."),
        corpusCase(.events, "The store closes Sunday", count: 1, route: [.memory], due: [nil]),
        corpusCase(.events, "Actually no wait, Maya's swim lesson moved to Thursday, not Wednesday.", count: 1,
                   type: [.event], route: [.today], person: [nil], due: [CorpusDate(month: 8, day: 6, hour: nil)],
                   note: "A retraction with nothing before it is throat-clearing; a lesson moved to a day is a plan, and \"Swim Lesson\" is nobody."),
        corpusCase(.events, "Okay so the standup moved to nine fifteen starting next Monday.", count: 1,
                   due: [CorpusDate(month: 8, day: 10, hour: 9, minute: 15)],
                   note: "The spoken minute behind the new hour was dropped."),
        corpusCase(.events, "Tell Nina the brunch is moved to 11.", count: 1, person: ["Nina"], due: [nil],
                   note: "The brunch's new time is the message, not when to tell her."),
        corpusCase(.events, "Schedule the dog's grooming appointment for Saturday morning.", count: 1,
                   type: [.task], person: [nil], due: [CorpusDate(month: 8, day: 8, hour: 9, minute: 0)],
                   note: "An errand that mentions an appointment is an errand, and the dog is not a person."),
        corpusCase(.events, "Finish the slides for the board meeting next thursday at 2", count: 1,
                   type: [.task], due: [CorpusDate(month: 8, day: 13, hour: 14, minute: 0)]),
        corpusCase(.events, "Meet Sam for dinner at 7", count: 1, type: [.event], person: ["Sam"],
                   due: [CorpusDate(month: 8, day: 3, hour: 19, minute: 0)]),
        corpusCase(.events, "Transfer $400 to savings on the 1st.", count: 1, type: [.task], route: [.today],
                   due: [CorpusDate(month: 9, day: 1, hour: nil)]),
        corpusCase(.events, "The lease on the apartment ends in November.", count: 1, route: [.memory], due: [nil],
                   note: "A month with no day is knowledge; this was a Today event with no date."),
        corpusCase(.events, "I told Sarah I'd drop off the casserole dish on Sunday.", count: 1, route: [.today],
                   person: ["Sarah"], due: [CorpusDate(month: 8, day: 9, hour: nil)],
                   note: "A promise the person made is theirs to keep; \"Sarah I'd\" was the person before."),
        corpusCase(.events, "i mean the meeting with legal is next tuesday not this one.", count: 1,
                   person: [nil], due: [CorpusDate(month: 8, day: 11, hour: nil)],
                   note: "Legal is a department."),
        corpusCase(.events, "Ravi recommended the wine bar on Ossington.", count: 1, route: [.memory], person: ["Ravi"]),
        corpusCase(.events, "call about the water heater warranty", count: 1, type: [.task], route: [.today]),
        corpusCase(.events, "Costco run tonight: milk, eggs, coffee.", count: 3, type: [.shopping, .shopping, .shopping],
                   due: [CorpusDate(month: 8, day: 3, hour: 20, minute: 0), CorpusDate(month: 8, day: 3, hour: 20, minute: 0), CorpusDate(month: 8, day: 3, hour: 20, minute: 0)],
                   note: "A store run with a colon list is a shopping list; this was a Memory note."),
        corpusCase(.events, "Groceries tonight: eggs, milk", count: 2, type: [.shopping, .shopping]),
        corpusCase(.events, "book the accountant for tax planning before end of quarter", count: 1,
                   due: [CorpusDate(month: 9, day: 30, hour: nil)],
                   note: "End of quarter and end of year are the same deadline shape as end of month; this had no date."),
        corpusCase(.events, "invoice 1042 is thirty days overdue chase it", count: 1, type: [.task], route: [.today]),
        corpusCase(.events, "i keep forgetting the tire pressure should be 35 psi front and 33 rear", count: 1,
                   route: [.memory], title: ["The tire pressure should be 35 psi front and 33 rear"],
                   note: "\"I keep forgetting\" with a fact behind it keeps the fact; with \"to\" it is an errand."),
        corpusCase(.events, "I keep forgetting to call Mom", count: 1, route: [.today], title: ["Call Mom"], person: ["Mom"]),
        corpusCase(.events, "Let's order the new filters for the furnace this week", count: 1, type: [.task], route: [.today],
                   title: ["Order the new filters for the furnace this week"],
                   note: "A proposal to oneself with an errand in it is the errand; this was a note with \"Let's\" on the title."),
        corpusCase(.events, "send the W9 to Northwind accounting", count: 1, person: [nil],
                   note: "A name followed by a department is an organisation."),
        corpusCase(.events, "follow up with unit 4 landlord about the lease renewal", count: 1, person: [nil],
                   note: "Filed a person called Unit."),
        corpusCase(.events, "Bring an umbrella tomorrow it's supposed to rain", count: 1, person: [nil],
                   due: [CorpusDate(month: 8, day: 4, hour: nil)],
                   note: "An infinitive \"to\" leads to a verb, not a recipient; this filed a person called Rain."),
        corpusCase(.events, "call the vet about max's medication", count: 1, title: ["Call the vet about Max's medication"],
                   note: "A possessive is still the name in the title."),
        corpusCase(.events, "email Priya the budget spreadsheet or whatever", count: 1,
                   title: ["Email Priya the budget spreadsheet"], person: ["Priya"],
                   note: "A hedge on the tail is not part of the errand; the words stay in the quote."),
        corpusCase(.events, "the car takes 5W-30 and it needs about five quarts", count: 1, route: [.memory],
                   title: ["The car takes 5W-30 and it needs about five quarts"],
                   note: "\"About\" is rewritten to \"around\" only beside a clock; a quantity keeps the person's word."),
        corpusCase(.events, "we need eggs milk and olive oil for the meal prep", count: 1, type: [.shopping], route: [.today],
                   note: "A need with nothing but products behind it is a shopping list; this was a Memory note."),
        corpusCase(.events, "While I'm out there grab stamps", count: 1, route: [.today]),
        corpusCase(.events, "the plant nursery on Dundas closes at 6 on weekdays", count: 1, route: [.memory],
                   due: [nil], recurs: [nil],
                   note: "A descriptive schedule is knowledge: this was a recurring 6 AM task on Today."),
        corpusCase(.events, "Log the meter reading every day at 1:30 AM", count: 1, type: [.task], route: [.today],
                   recurs: [CorpusRecurrence(frequency: .daily)],
                   note: "An instruction with a recording verb keeps its series; only a described schedule loses one."),

        // A stated day and a stated clock is a calendar commitment whatever the
        // subject noun is. "The recital is Saturday at two" worked only because
        // "recital" was on `scheduledNoun`; the identical sentence about soccer
        // practice lost its route and its date together.
        corpusCase(.events, "Soccer practice is Tuesday at five.",
                   count: 1, type: [.event], route: [.today], kind: [.exactDateTime],
                   due: [CorpusDate(month: 8, day: 4, hour: 17)]),
        corpusCase(.events, "Nadia's birthday is October 12.",
                   count: 1, type: [.note], route: [.memory], person: ["Nadia"], due: [nil],
                   note: "Guard: a date with no clock stays the fact about a person that scheduledNoun's exclusion intends."),

    ]

    // MARK: - Pronouns, names and possessives
    //
    // Who a capture is about decides where it files, whose row it appears on,
    // and who a message would be addressed to. A wrong answer here is visible
    // and occasionally embarrassing; an invented one is worse than none.
    static let pronouns: [CorpusCase] = [
        corpusCase(.pronouns, "Call her tomorrow", count: 1, person: [nil], review: [true],
                   note: "No antecedent anywhere in the capture. Ask; do not attach the last person seen."),
        corpusCase(.pronouns, "Remind me to send it to him", count: 1, person: [nil],
                   note: "\"Him\" names nobody the app knows."),
        corpusCase(.pronouns, "Tell them the launch moved", count: 1, route: [.today], person: [nil]),
        corpusCase(.pronouns, "Her flight lands at 6", count: 1, person: [nil],
                   due: [CorpusDate(month: 8, day: 3, hour: 18)]),
        corpusCase(.pronouns, "Catherine said she needs the blue folder", count: 1, route: [.memory],
                   person: ["Catherine"],
                   note: "\"She\" is Catherine, named in the same sentence. This is the resolvable case that \"call her tomorrow\" is not."),
        corpusCase(.pronouns, "Alex's mom is visiting", count: 1, route: [.memory], person: ["Alex"]),
        corpusCase(.pronouns, "Call Catherine's assistant", count: 1, route: [.today],
                   person: ["Catherine's assistant"],
                   note: "The possessive names the person being called, not Catherine."),
        corpusCase(.pronouns, "I need to return Priya's book", count: 1, route: [.today], person: ["Priya"]),
        corpusCase(.pronouns, "Mom's birthday is Friday", count: 1, route: [.memory], person: ["Mom"],
                   note: "Contract corrected during review. The original expectation gave this a due date, which would have made a birthday an appointment on Today. Speak It already files a person's birthday as knowledge under that person — the behaviour `SwiftDataThoughtRepositoryTests` pins for \"Alex's birthday is October 12\" — and an annual fact about somebody is not this week's commitment. What matters is that it is findable under Mom."),
        corpusCase(.pronouns, "Remember Catherine's husband is called David", count: 1, route: [.memory],
                   person: ["Catherine"],
                   note: "Decided 2026-09-08: filed under Catherine, the person the speaker knows and will look under. \"Is called\" names David; nobody phoned him, which is what the actor rule used to read."),
        corpusCase(.pronouns, "Alex and his brother are coming Friday", count: 1, person: ["Alex"],
                   due: [CorpusDate(month: 8, day: 7, hour: nil)]),
        corpusCase(.pronouns, "Pick up my sister from the airport", count: 1, type: [.task], route: [.today]),
        corpusCase(.pronouns, "Text my brother about the game", count: 1, type: [.personFollowUp],
                   route: [.today]),
        corpusCase(.pronouns, "My dentist's office called", count: 1, route: [.memory], delivery: [.none]),
        corpusCase(.pronouns, "Call the O'Briens tomorrow", count: 1, route: [.today],
                   due: [CorpusDate(month: 8, day: 4, hour: nil)]),
        corpusCase(.pronouns, "It's on my desk", count: 1, route: [.memory], remind: [nil]),
        corpusCase(.pronouns, "Give Mom's recipe to Catherine", count: 1, route: [.today],
                   person: ["Catherine"],
                   note: "Decided 2026-09-08: the recipient is who the errand is with, and a possessive name is the object's determiner — \"Mom's recipe\" has the shape of \"the recipe\", so the errand reaches Today."),
        corpusCase(.pronouns, "Send Alex's invoice to Priya", count: 1, route: [.today], person: ["Priya"]),
        corpusCase(.pronouns, "Return Priya's book to Sam", count: 1, route: [.today], person: ["Sam"]),
        corpusCase(.pronouns, "Bring the laptop to work", count: 1, route: [.today], person: [nil],
                   note: "A transfer reaches a place as often as a person; \"work\" is nobody."),
        corpusCase(.pronouns, "Remind me to ask Dr. Okonkwo's office about the referral", count: 1,
                   route: [.today], delivery: [.none], review: [true],
                   note: "Contract corrected during review. The original expectation asserted a notification, but no time was ever named — there is nothing to schedule, so the honest outcome is Today plus a request for the missing time, not a delivery promise the app cannot keep."),
    ]

    // MARK: - Compositions
    //
    // Everything at once. These are not new features; every ingredient in this
    // family already passes on its own elsewhere in the corpus. What is being
    // tested is whether the features are independent, and the honest prior is
    // that some of them are not — a correction that works, applied inside a
    // recurrence that works, next to a cancellation that works, is three
    // passing rules and one possible wrong item.
    static let compositions: [CorpusCase] = [
        corpusCase(.compositions,
                   "Remind me to call Mom tomorrow, actually Friday, and remember she needs the blue folder",
                   count: 2, route: [.today, .memory], person: ["Mom", "Mom"],
                   remind: [CorpusDate(month: 8, day: 7, hour: 9), nil],
                   note: "Correction inside clause one, a memory in clause two, and a pronoun in clause two that refers to clause one."),
        corpusCase(.compositions,
                   "Don't remind me about the dentist anymore, but remind me to call Mom at six",
                   count: 1, route: [.today], person: ["Mom"],
                   remind: [CorpusDate(month: 8, day: 3, hour: 18)],
                   operation: [.cancel], operationTarget: ["dentist"],
                   note: "A cancellation and a creation in one breath. Either half swallowing the other is a wrong item."),
        corpusCase(.managingItems, "Cancel my Netflix subscription", count: 1, type: [.task], route: [.today],
                   note: "An arrangement with a company is the person's errand, not an operation on a stored row; read as one it deleted a matching reminder and left nothing to do."),
        corpusCase(.managingItems, "Cancel the gym membership before the end of the month", count: 1, route: [.today],
                   due: [CorpusDate(month: 8, day: 31, hour: nil)]),
        corpusCase(.compositions, "Don't fix the sink", count: 0,
                   operation: [.cancel], operationTarget: ["fix the sink"],
                   note: "The detector reads the shared errand vocabulary: this cancels a matching reminder as \"don't call the plumber\" does, and is preserved as a note when nothing matches."),
        corpusCase(.compositions, "When I get home remind me to call Alex, actually Catherine",
                   count: 1, person: ["Catherine"],
                   place: [CorpusPlace(event: .arrive, place: .home, repeats: false)],
                   note: "A correction after a place trigger. The place must survive the correction and the correction must not become a second geofence."),
        corpusCase(.compositions, "Every Friday at five remind me to submit the report, except this Friday",
                   count: 1,
                   recurs: [CorpusRecurrence(frequency: .weekly, interval: 1, weekdays: [6])],
                   review: [true],
                   note: "Exceptions to a series are unmodelled. The series is right; the exception must be surfaced rather than silently dropped, because dropping it fires on the one day the person excluded."),
        corpusCase(.compositions, "I was supposed to call Mom yesterday but she already called me",
                   count: 1, route: [.memory], person: ["Mom"], delivery: [.none],
                   note: "An outstanding obligation discharged in the same sentence. \"I was supposed to\" alone would put this on Today, and here it must not."),
        corpusCase(.compositions, "Call Alex and Alexa tomorrow at five", count: 2,
                   type: [.personFollowUp, .personFollowUp], route: [.today, .today],
                   person: ["Alex", "Alexa"],
                   due: [CorpusDate(month: 8, day: 4, hour: 17), CorpusDate(month: 8, day: 4, hour: 17)],
                   note: "Near-identical names, split, both inheriting one shared time."),
        corpusCase(.compositions, "Remember Catherine said I need to call Alex Friday", count: 1,
                   route: [.today], person: ["Alex"], due: [CorpusDate(month: 8, day: 7, hour: nil)],
                   note: "Reported speech wrapping a real obligation. \"Remember\" is how it was learned, not what it is — filing this only in Memory means the call is missed. The person is the one inside the obligation, not the one who relayed it."),
        // Authored 2026-09-09 from three domain batches (work, family,
        // money) and the people sweep's P2 cluster.
        corpusCase(.compositions, "Call Mom tomorrow and my sister Friday", count: 2, person: ["Mom", nil],
                   due: [CorpusDate(month: 8, day: 4, hour: nil), CorpusDate(month: 8, day: 7, hour: nil)],
                   note: "P2: \"my sister\" is a second person, not Mom's compound subject; was one row."),
        corpusCase(.compositions, "Text Alex tonight and my brother tomorrow", count: 2,
                   due: [CorpusDate(month: 8, day: 3, hour: 20, minute: 0), CorpusDate(month: 8, day: 4, hour: nil)],
                   note: "Was one row dated tomorrow 8 PM: Alex's \"tonight\" was hijacked."),
        corpusCase(.compositions, "Call the bank about the $89 charge I don't recognize.", count: 1, route: [.today],
                   note: "\"Charge\" behind an amount is a noun; this was cut into two tasks."),
        corpusCase(.compositions, "Ask Nadia to review the security section of the design doc before the Friday sign off.",
                   count: 1, person: ["Nadia"], due: [CorpusDate(month: 8, day: 7, hour: nil)],
                   note: "\"Sign off\" behind \"the Friday\" is a noun; this produced a task called Sign off."),
        corpusCase(.compositions, "buy sunscreen and a travel adapter before we leave", count: 2,
                   type: [.shopping, .shopping], route: [.today, .today],
                   note: "The trailing condition is context; the adapter used to go to Memory as a note."),
        corpusCase(.compositions, "Split the cabin rental with Tom and Alice, it's $1200 total so $400 each.",
                   count: 1, route: [.today],
                   note: "Two companions of one \"with\"; the \"and\" is not a boundary and Alice was being dropped."),
        corpusCase(.compositions, "finish the laundry, unload the dishwasher, and vacuum the living room", count: 3,
                   route: [.today, .today, .today]),
        corpusCase(.compositions, "okay so the midterm is on the 15th and it covers everything through chapter nine.",
                   count: 2, route: [.today, .memory], due: [CorpusDate(month: 8, day: 15, hour: nil), nil],
                   note: "A dated exam is a commitment; \"midterm\" joined the scheduled nouns."),
        corpusCase(.compositions, "Send the invoice to accounts payable by end of day and cc Dana.", count: 2,
                   route: [.today, .today], person: [nil, "Dana"],
                   note: "Accounts payable is a department; \"cc\" is a verb."),
        // Authored 2026-09-09, second agent round (freelancer, fitness and
        // errands, row titles).
        corpusCase(.compositions, "email the Halden contract to legal and get it back by Friday", count: 1,
                   route: [.today], due: [CorpusDate(month: 8, day: 7, hour: nil)],
                   note: "A conjunct whose object is a pronoun pointing back is the same errand; this left \"Get it back by Friday\" with no referent."),
        corpusCase(.compositions, "Let's invite Tom and Rachel over for dinner on Saturday", count: 1,
                   title: ["Invite Tom and Rachel over for dinner on Saturday"], due: [CorpusDate(month: 8, day: 8, hour: nil)],
                   note: "The particle behind the second name belongs to the shared verb; this was \"Let's invite Tom\" plus a headless \"Rachel over for dinner\"."),
        corpusCase(.compositions, "Marcus prefers phone calls over email he never reads email", count: 1,
                   route: [.memory], person: ["Marcus"],
                   note: "The word behind a verb is its object: this was cut before \"phone\"."),
        corpusCase(.compositions, "i need to buy a new mic stand and a pop filter for client calls", count: 2,
                   type: [.shopping, .shopping], route: [.today, .today],
                   note: "A purpose on the tail is context for verb sharing; the pop filter went to Memory."),
        corpusCase(.compositions, "i need to go to the bank Thursday to deposit the cheque and while I'm out there grab stamps",
                   count: 2, route: [.today, .today], due: [CorpusDate(month: 8, day: 6, hour: nil), nil],
                   note: "A fronted condition may close on a pronoun or particle before its errand."),
        corpusCase(.compositions, "Priya said I should call the landlord", count: 1,
                   route: [.today], person: ["Priya"],
                   note: "The obligation names nobody, so the person who relayed it is who the row is about."),
        corpusCase(.compositions, "Remind me at the pharmacy to pick up my prescription and buy toothpaste",
                   count: 2, route: [.today, .today],
                   place: [CorpusPlace(event: .arrive, place: .named("the pharmacy"), repeats: false),
                           CorpusPlace(event: .arrive, place: .named("the pharmacy"), repeats: false)],
                   note: "Two errands, one trigger. Both must inherit the place, the same way both inherit a shared time."),

        corpusCase(.compositions, "Don't let me forget to call Mom, and don't remind me about the dentist",
                   count: 1, route: [.today], person: ["Mom"],
                   operation: [.cancel], operationTarget: ["dentist"],
                   note: "The same word means opposite things twice in one sentence: emphasis first, cancellation second."),
        corpusCase(.compositions, "Don't buy milk but do pick up bread", count: 1, route: [.today],
                   operation: [.cancel], operationTarget: ["buy milk"]),
        corpusCase(.compositions, "Don't call Catherine tomorrow, call her Friday", count: 1,
                   person: ["Catherine"], due: [CorpusDate(month: 8, day: 7, hour: nil)],
                   note: "Contract corrected during review. The original expectation asserted no cancellation at all, which overreached: if a call is already scheduled for tomorrow, cancelling it is right. What is not negotiable is that the Friday call exists — a sentence that names a new day must never end with nothing on it."),
        corpusCase(.compositions, "Cancel the dentist and book the doctor instead", count: 1,
                   route: [.today], operation: [.cancel]),
        corpusCase(.compositions, "I already called Mom but I still need to call Catherine", count: 1,
                   route: [.today], person: ["Catherine"], operation: [.complete],
                   note: "One completion and one outstanding obligation, sharing a verb."),
        corpusCase(.compositions, "I don't need to call Mom anymore, and I already bought the milk",
                   count: 0, operation: [.cancel, .complete],
                   note: "Two different operations, no creation at all."),
        corpusCase(.compositions, "I still haven't called Catherine and I already emailed Alex", count: 1,
                   route: [.today], person: ["Catherine"], operation: [.complete]),

        corpusCase(.compositions, "Remind me tomorrow at five, no actually when I get home", count: 1,
                   remind: [nil], place: [CorpusPlace(event: .arrive, place: .home, repeats: false)],
                   note: "A correction from a time to a place. The abandoned time must not stay scheduled."),
        corpusCase(.compositions, "Remind me when I get home, actually tomorrow at five", count: 1,
                   remind: [CorpusDate(month: 8, day: 4, hour: 17)], place: [nil],
                   note: "The same correction in reverse. The abandoned geofence must not stay armed."),
        corpusCase(.compositions, "Buy milk when I get home, actually when I get to the store", count: 1,
                   type: [.shopping], route: [.today],
                   place: [CorpusPlace(event: .arrive, place: .named("the store"), repeats: false)],
                   note: "Route added during review. Scoring only the type hid the consequence: a shopping errand read as a note leaves Today and the milk is never bought."),
        corpusCase(.compositions, "Call Catherine tomorrow at five and remind me an hour before", count: 1,
                   person: ["Catherine"], due: [CorpusDate(month: 8, day: 4, hour: 17)],
                   remind: [CorpusDate(month: 8, day: 4, hour: 16)],
                   note: "One item carrying both fields, with the reminder stated relative to the due time. This is the case \"remind me an hour before the meeting\" cannot do, because here the anchor is present."),
        corpusCase(.compositions, "Remind me in 20 minutes, and again in an hour", count: 2,
                   remind: [CorpusDate(month: 8, day: 3, hour: 10, minute: 20),
                            CorpusDate(month: 8, day: 3, hour: 11)],
                   note: "Two reminders about one subject."),

        corpusCase(.compositions, "Buy milk, eggs and bread tomorrow, and call Mom Friday", count: 4,
                   type: [.shopping, .shopping, .shopping, .personFollowUp],
                   person: [nil, nil, nil, "Mom"],
                   due: [CorpusDate(month: 8, day: 4, hour: nil), CorpusDate(month: 8, day: 4, hour: nil),
                         CorpusDate(month: 8, day: 4, hour: nil), CorpusDate(month: 8, day: 7, hour: nil)],
                   note: "A dated grocery list splits into checkable rows that share the list's day — Today shows them as one dated list card, and same-moment reminders from one capture coalesce into a single notification — while the call keeps its own day."),
        corpusCase(.compositions, "Buy milk and don't forget to call Mom", count: 2,
                   route: [.today, .today], person: [nil, "Mom"], operation: []),
        corpusCase(.compositions, "Remember the wifi password is maple syrup and buy batteries tomorrow",
                   count: 2, route: [.memory, .today],
                   due: [nil, CorpusDate(month: 8, day: 4, hour: nil)]),
        corpusCase(.compositions, "Remember Alex's number is 555 0134 and call him tomorrow", count: 2,
                   route: [.memory, .today], person: ["Alex", "Alex"], remind: [nil, nil],
                   note: "A number that is not a time, and a pronoun in the second clause pointing at the first."),
        corpusCase(.compositions, "I met Catherine yesterday and she said to call Alex Friday", count: 2,
                   route: [.memory, .today], person: ["Catherine", "Alex"],
                   note: "A past record and a future obligation, split correctly, each about a different person."),
        corpusCase(.compositions, "Tell Alex the meeting moved to Thursday and remind me to book the room",
                   count: 2, route: [.today, .today], person: ["Alex", nil]),
        corpusCase(.compositions, "Remind me tomorrow morning to email Professor Chen and Professor Diallo",
                   count: 2, route: [.today, .today],
                   remind: [CorpusDate(month: 8, day: 4, hour: 9), CorpusDate(month: 8, day: 4, hour: 9)]),
        corpusCase(.compositions, "Pick up the prescription at the pharmacy and gas at the station", count: 2,
                   route: [.today, .today],
                   title: ["Pick up the prescription at the pharmacy", "Pick up gas at the station"],
                   note: "Decided 2026-09-08: the conjunct repeats the place frame with a new object in front and is sharing the verb. Two places are two errands, and each can be ticked off on its own."),
        corpusCase(.compositions, "Buy toothpaste, uh, and toothbrush, no wait just toothpaste", count: 1,
                   type: [.shopping], route: [.today],
                   note: "Filler, an addition, and a correction that retracts the addition — all inside one shopping item."),

        corpusCase(.compositions,
                   "The meeting is Friday at 3, remind me Thursday at 5, and Catherine is presenting",
                   count: 2, route: [.today, .memory], person: [nil, "Catherine"],
                   due: [CorpusDate(month: 8, day: 7, hour: 15), nil],
                   remind: [CorpusDate(month: 8, day: 6, hour: 17), nil],
                   note: "Three clauses, two items: the reminder belongs to the meeting, the fact about Catherine does not."),
        corpusCase(.compositions,
                   "Every day at nine remind me to take my pills, and remember the pharmacy closes at six",
                   count: 2, route: [.today, .memory],
                   remind: [CorpusDate(month: 8, day: 4, hour: 9), nil],
                   recurs: [CorpusRecurrence(frequency: .daily, interval: 1), nil],
                   note: "A clock inside a memory must not schedule anything."),
        corpusCase(.compositions,
                   "Every morning at seven remind me to take my vitamins, and stop reminding me about the gym",
                   count: 1, remind: [CorpusDate(month: 8, day: 4, hour: 7)],
                   recurs: [CorpusRecurrence(frequency: .daily, interval: 1)],
                   operation: [.cancel], operationTarget: ["gym"],
                   note: "A recurrence and a cancellation of a different recurrence, in one sentence."),
        corpusCase(.compositions,
                   "Remind me every Friday to submit the report, and Catherine needs a copy",
                   count: 2, route: [.today, .memory], person: [nil, "Catherine"],
                   recurs: [CorpusRecurrence(frequency: .weekly, interval: 1, weekdays: [6]), nil],
                   note: "The recurrence must not leak onto the memory."),
        corpusCase(.compositions,
                   "When I leave work remind me to buy milk, and every Sunday remind me to call Mom",
                   count: 2, person: [nil, "Mom"],
                   recurs: [nil, CorpusRecurrence(frequency: .weekly, interval: 1, weekdays: [1])],
                   place: [CorpusPlace(event: .leave, place: .work, repeats: false), nil],
                   note: "A place trigger and a time series side by side. Neither may cross into the other item."),
        corpusCase(.compositions,
                   "Every other Friday at five, remind me to submit the report and pay the contractor",
                   count: 2,
                   recurs: [CorpusRecurrence(frequency: .weekly, interval: 2, weekdays: [6]),
                            CorpusRecurrence(frequency: .weekly, interval: 2, weekdays: [6])],
                   note: "Both items inherit one series, the same way both inherit one time."),
        corpusCase(.compositions, "Set an alarm for 6 AM and remind me to pack my gym bag tonight", count: 2,
                   delivery: [.alarm, .notification],
                   remind: [CorpusDate(month: 8, day: 4, hour: 6), CorpusDate(month: 8, day: 3, hour: 20)],
                   note: "Two deliveries in one capture. A shared-delivery shortcut would make both alarms or both notifications."),
        corpusCase(.compositions, "Call Mom every Sunday, except when I'm travelling", count: 1,
                   person: ["Mom"],
                   recurs: [CorpusRecurrence(frequency: .weekly, interval: 1, weekdays: [1])],
                   review: [true],
                   note: "A conditional exception, which is unmodelled and must be surfaced."),
        corpusCase(.compositions, "Don't schedule the meeting Friday, move it to Monday", count: 1,
                   due: [CorpusDate(month: 8, day: 10, hour: nil)],
                   note: "\"Don't\" attached to the old day, not to the meeting. Monday is the answer and Friday is what it replaced."),
        corpusCase(.compositions, "Remind me at five to call Catherine at the pharmacy", count: 1,
                   remind: [CorpusDate(month: 8, day: 3, hour: 17)], place: [nil],
                   severityCeiling: .metadata,
                   note: "Arguable: the pharmacy is where Catherine is, not a trigger for me. Recorded, not gated — but a geofence here would fire in the wrong place."),
        corpusCase(.compositions, "Uh, so, don't forget I already paid the rent", count: 1, route: [.memory],
                   severityCeiling: .metadata,
                   note: "Arguable: \"don't forget\" asks to keep it, \"already\" closes it. Recording it is the safer of the two. Recorded, not gated."),
    ]

    static let all: [CorpusCase] =
        deadlines + alarms + events + pronouns + compositions
}
